name: Metrics

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------------ #
      # The 3D isometric contribution calendar
      # ------------------------------------------------------------------ #
      - name: Isometric contribution calendar
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          filename: assets/metrics.isocalendar.svg
          base: ""
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year



